### ISSUE TITLE
The first practice

### ISSUE THREAD

**Issue by Vannguyen0520** [Vannguyen0520/HelloJava#1]
Hi, all.
## Please, help me to solve my issue.
Because I just start with Jenkins, I tried to find some information from google, but I didn't fix this. Thanks for helping me.
I have a issue with the first practice. This is I want to get my code from GitHub, but I couldn't. Because there are some issues with my project. They are:
1.There was red message : "Failed to connect to repository : Failed to create http proxy uri"  under link where I pasted my project from GitHub. Although I configured in 
Configure System and Global Tool Configuration.
2. There was error after I run my project: 
Started by user Admin
[EnvInject] - Loading node environment variables.
Building on master in workspace C:\Program Files (x86)\Jenkins\workspace\Helloword
 > c:\Program Files\Git\bin\git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > c:\Program Files\Git\bin\git.exe config remote.origin.url https://github.com/Vannguyen0520/HelloJava.git # timeout=10
Fetching upstream changes from https://github.com/Vannguyen0520/HelloJava.git
 > c:\Program Files\Git\bin\git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
Setting http proxy: https://wiki.jenkins-ci.org/display/JENKINS/JDK+Parameter+Plugin:0
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/Vannguyen0520/HelloJava.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:817)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1084)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1212)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:566)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:491)
	at hudson.model.Run.execute(Run.java:1737)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
Caused by: hudson.plugins.git.GitException: Failed to create http proxy uri
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1637)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:352)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:815)
	... 11 more
Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 14: http://[https://wiki.jenkins-ci.org/display/JENKINS/JDK+Parameter+Plugin]:0
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.failExpecting(Unknown Source)
	at java.net.URI$Parser.parseServer(Unknown Source)
	at java.net.URI$Parser.parseAuthority(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1633)
	... 14 more
ERROR: Error fetching remote repo 'origin'
Finished: FAILURE

**Comment by Vannguyen0520** [comment]
Setup proxy for advance (configure system\Plugins)
